elasticsearch:
  build: elasticsearch/
  ports:
    - "9200:9200"
  volumes:
    - ./data:/usr/share/elasticsearch/data
logstash:
  image: logstash:latest
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
  ports:
    - "5000:5000"
  links:
    - elasticsearch
kibana:
  build: kibana/
  volumes:
    - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
  ports:
    - "5601:5601"
  links:
    - elasticsearch
nginx:
  image: nginx
  ports:
    - "80:80"
  volumes:
    - ./nginx/conf.d/:/etc/nginx/conf.d
    - ./nginx/htpasswd/htpasswd:/etc/nginx/htpasswd
    - ..:/srv
  links:
    - kibana